export {default as Home} from "./Home/Home"
export {default as Login} from "./Login/Login"
export {default as Cadastro} from "./Cadastro/Cadastro"
export {default as Perfil} from "./Perfil/Perfil"
export {default as Usuario} from "../Components/Usuario/Usuario"